openapi: 3.0.n
title: SKHUINFO API
description: SKHUINFO API

servers:
  - url: https://skhuinfo.sleepy-owl.com/v1
    descroption: Production Server

paths:
  /meals/ids:
    get:
      summary: 학식 게시물 ID 목록 조회 
      responses:
        '200':
          content:
            application/json:
              schema: 
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
        
  /meals/{id}:
    get:
      summary: 학식 데이터 조회
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: false
          description: 학식 게시물 ID
          example: 389
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        day:
                          type: string
                          description: 요일
                          example: 월요일
                        date:
                          type: string
                          description: 날짜
                          example: 2019-12-02
                        lunch:
                          type: object
                          description: 점심 식단
                          properties:
                            a:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 사골순대국\n 쌀밥\n미트볼조림 ...
                                calorie:
                                  type: string
                            b:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 돈까스\n 함박스테이크
                                calorie:
                                  type: string
                            c:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 라면\n 공기밥
                                calorie:
                                  type: string
                        dinner:
                          type: object
                          description: 저녁 식단
                          properties:
                            a:
                              type: object
                              properties:
                                diet:
                                  type: string
                                calorie:
                                  type: string
  /schedules/{year}/{month}:     
    get:
      summary: 학사일정 조회
      parameters:
        - in: path
          name: year
          schema:
            type: integer
          required: true
          description: 년도
          example: 2020
        - in: path
          name: month
          schema:
            type: integer
          required: true
          description: 월
          example: 8
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  schedules:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: string
                          description: 기간
                          example: 07-20 ~ 07-24
                        content:
                          type: string
                          description: 일정
                          example: 2020-2 복학신청기간
                       
