openapi: 3.0.n
title: SKHUINFO API
description: SKHUINFO API

servers:
  - url: https://skhuinfo.sleepy-owl.com/v1
    descroption: Production Server

paths:
  /contacts/orgs/{keyword}:
    get:
      description: 연락처가 있는 학내 기관 목록 조회. 키워드 없는 경우 모든 기관 목록 조회.
      parameters:
        - in: path
          name: keyword
          required: false
          schema:
            type: string
          description: 학내 기관 검색 키워드(선택)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  orgs:
                    type: array
                    example:
                      - 교무처
                      - 입학홍보처
                      - 기획처
                      - ...
                    items:
                      type: string
  /contacts/find:
    get:
      description: 학내기관 연락처 검색
      parameters:
        - in: query
          name: org
          required: false
          description: 검색 키워드 - 기관/조직 이름
          schema:
            type: string
          example: 교무처
        - in: query
          name: name
          required: false
          description: 검색 키워드 - 이름
          schema:
            type: string
          example: 홍길동
        - in: query
          name: phone
          required: false
          description: 검색 키워드 - 전화번호
          schema:
            type: string
          example: 2610-4114
        - in: query
          name: email
          required: false
          description: 검색 키워드 - 이메일 주소
          schema:
            type: string
          example: hello@example.com
        - in: query
          name: desc 
          required: false
          description: 그 외 정보 검색 키워드
          schema:
            type: string
          example: 교원인사
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      type: object
                      properties:
                        org:
                          type: string
                          description: 소속 기관/조직
                        name:
                          type: string
                          description: 이름
                        phone:
                          type: string
                          description: 전화번호
                        email:
                          type: string
                          description: 이메일 주소
                        desc:
                          type: string
                          description: 그 외 정보 

  /meals/ids:
    get:
      summary: 학식 게시물 ID 목록 조회 
      responses:
        '200':
          content:
            application/json:
              schema: 
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          date:
                            type: string
        
  /meals/get:
    get:
      summary: 학식 데이터 조회, 아무 입력이 없으면 오늘에 해당하는 식단표 검색 후 있으면 조회, 없으면 에러 반환합니다.
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: false
          description: 학식 게시물 ID
          example: 389
        - in: query
          name: day
          required: false
          description: 주간 학식 시간표에서 조회할 요일(월~토, 0~5)
          schema:
            type: integer
          example: 0
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        day:
                          type: string
                          description: 요일
                          example: 월요일
                        date:
                          type: string
                          description: 날짜
                          example: 2019-12-02
                        lunch:
                          type: object
                          description: 점심 식단
                          properties:
                            a:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 사골순대국\n 쌀밥\n미트볼조림 ...
                                calorie:
                                  type: string
                            b:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 돈까스\n 함박스테이크
                                calorie:
                                  type: string
                            c:
                              type: object
                              properties:
                                diet:
                                  type: string
                                  example: 라면\n 공기밥
                                calorie:
                                  type: string
                        dinner:
                          type: object
                          description: 저녁 식단
                          properties:
                            a:
                              type: object
                              properties:
                                diet:
                                  type: string
                                calorie:
                                  type: string
  /schedules/{year}/{month}:     
    get:
      summary: 학사일정 조회
      parameters:
        - in: path
          name: year
          schema:
            type: integer
          required: true
          description: 년도
          example: 2020
        - in: path
          name: month
          schema:
            type: integer
          required: true
          description: 월
          example: 8
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  schedules:
                    type: array
                    items:
                      type: object
                      properties:
                        period:
                          type: string
                          description: 기간
                          example: 07-20 ~ 07-24
                        content:
                          type: string
                          description: 일정
                          example: 2020-2 복학신청기간